# Generated by Django 2.2.3 on 2019-07-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('has_size', models.BooleanField()),
                ('has_topping', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('has_size', models.BooleanField()),
                ('has_topping', models.BooleanField()),
                ('price_small', models.FloatField()),
                ('price_large', models.FloatField()),
                ('available_toppings', models.ManyToManyField(blank=True, to='shopping.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Item_price_no_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_price_by_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_small', models.FloatField()),
                ('price_large', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Item')),
            ],
        ),
    ]
