# Generated by Django 2.2.3 on 2019-07-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_sub_has_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='available_toppings',
        ),
        migrations.AddField(
            model_name='sub',
            name='available_toppings',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
