# Generated by Django 2.2.3 on 2019-07-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20190728_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('items', models.TextField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
