# Generated by Django 2.2.3 on 2019-08-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
